import { doc, setDoc } from "firebase/firestore";
import { db } from "./firebase";
import { Section } from "../types/tasks";

export const createUserTasks = async (userId: string) => {
  const tasksList: Section[] = [
    {
      id: "brewing_basics",
      title: "Brewing Basics",
      tasks: [
        {
          id: "coffee_to_water_ratio",
          number: 1,
          title: "Coffee-to-Water Ratio",
          description:
            "Brew coffee using a 1:16 ratio (e.g., 20g coffee to 320g water).",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "taste_difference",
          number: 2,
          title: "Taste the Difference",
          description: "Compare light vs. dark roast coffee side by side.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "french_press_plunge",
          number: 3,
          title: "French Press Plunge",
          description:
            "Brew coffee using a French Press with a 4-minute steep time.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "test_grind_sizes",
          number: 4,
          title: "Test Grind Sizes",
          description: "Try coffee with coarse, medium, and fine grinds.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "water_wisdom",
          number: 5,
          title: "Water Wisdom",
          description: "Brew coffee with distilled water vs. filtered water.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "pour_over_practice",
          number: 6,
          title: "Pour-Over Practice",
          description:
            "Brew a cup using a pour-over method, pouring water in a slow spiral.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "cold_brew_soak_1",
          number: 7,
          title: "Cold Brew Soak",
          description:
            "Make cold brew concentrate by steeping grounds in cold water for 12+ hours.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "master_moka_pot",
          number: 8,
          title: "Master the Moka Pot",
          description: "Make stovetop espresso using a Moka Pot.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "drip_it_good",
          number: 9,
          title: "Drip It Good",
          description: "Try a classic drip coffee.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "two_beans_one_brew",
          number: 10,
          title: "Two Beans, One Brew",
          description: "Mix two bean types and brew.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
      ],
    },
    {
      id: "global_coffee_tour",
      title: "Global Coffee Tour",
      tasks: [
        {
          id: "italian_espresso",
          number: 11,
          title: "Italian Espresso",
          description: "Drink espresso like Italians: quick & strong.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "colombian_supremo",
          number: 12,
          title: "Colombian Supremo",
          description:
            "Brew a pour-over with Colombian beans and taste their caramel sweetness.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "moroccan_spiced_coffee",
          number: 13,
          title: "Moroccan Spiced Coffee",
          description: "Brew with cinnamon and nutmeg.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "greek_frappe",
          number: 14,
          title: "Greek Frappé",
          description:
            "Shake instant coffee, water, sugar, and ice for a frothy frappé.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "french_cafe_au_lait",
          number: 15,
          title: "French Café au Lait",
          description: "Mix drip coffee with steamed milk.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "swedish_fika",
          number: 16,
          title: "Swedish Fika",
          description: "Enjoy coffee with a small pastry or bun.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "puerto_rican_cortado",
          number: 17,
          title: "Puerto Rican Café Cortao",
          description: "Mix equal parts espresso and steamed milk.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "vietnamese_iced_coffee",
          number: 18,
          title: "Vietnamese Iced Coffee",
          description:
            "Mix strong drip coffee with sweetened condensed milk over ice.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "viennese_melange",
          number: 19,
          title: "Viennese Melange",
          description: "Prepare coffee with steamed milk and whipped cream.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "brazilian_cafezinho",
          number: 20,
          title: "Brazilian Cafézinho",
          description: "Sweet and bold traditional coffee.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
      ],
    },
    {
      id: "creativity_skills",
      title: "Creativity & Skills",
      tasks: [
        {
          id: "new_cafe_visit",
          number: 21,
          title: "New Café Visit",
          description: "Try a coffee shop you've never been to before.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "flavor_mad_scientist",
          number: 22,
          title: "Flavor Mad Scientist",
          description:
            "Mix coffee with an unexpected ingredient (e.g., chili, lavender).",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "coffee_ice_cream_pairing",
          number: 23,
          title: "Coffee & Ice Cream Pairing",
          description: "Create a dessert combo with coffee.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "barista_for_a_day",
          number: 24,
          title: "Barista for a Day",
          description: "Practice latte art or milk frothing at home.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "signature_drink",
          number: 25,
          title: "Signature Drink",
          description: "Invent your own coffee drink and give it a cool name.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "spice_it_up",
          number: 26,
          title: "Spice It Up",
          description:
            "Add spices like cardamom, ginger, or cloves and rate the flavor.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "cold_brew_soak_2",
          number: 27,
          title: "Cold Brew Soak",
          description:
            "Make cold brew concentrate by steeping grounds in cold water for 12+ hours.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "coffee_inspired_bake",
          number: 28,
          title: "Coffee-Inspired Bake",
          description: "Bake coffee-infused cookies or tiramisu.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "blind_taste_test",
          number: 29,
          title: "Blind Taste Test",
          description: "Taste two coffees blindfolded and guess the bean.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
        {
          id: "travel_mug_adventure",
          number: 30,
          title: "Travel Mug Adventure",
          description: "Take coffee outside—park, hike, or walk.",
          createdAt: null,
          updatedAt: null,
          completed: false,
        },
      ],
    },
  ];

  await setDoc(doc(db, "tasks", userId), { tasksList });
};
